KPI:
  outputs:
    dev:
      dataset: dataobservability
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: '../google/google_credentials.json'
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GOOGLE_CLOUD_PROJECT') }}"
      threads: 1
      type: bigquery
  target: dev